name: airbnb_dbt

profile: airbnb_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_seed'
  airbnb_dbt:
    +schema: seed

models:
  airbnb_dbt:
    +static_analysis: strict

    # Materialize staging models as views
    staging:
      +database: AIRBNB_STAGING
      +schema: model
      +materialized: view

    # Materialize marts as tables
    marts:
      +database: AIRBNB_MART
      +schema: model
      +materialized: table


snapshots:
  airbnb_dbt:
    +database: AIRBNB_STAGING
    +schema: snapshot




   

