-- ================================================
-- Create Databases
-- ================================================
CREATE DATABASE IF NOT EXISTS AIRBNB_RAW;
CREATE DATABASE IF NOT EXISTS AIRBNB_STAGING;
CREATE DATABASE IF NOT EXISTS AIRBNB_MART;


-- ================================================
-- Create Schemas
-- ================================================
CREATE SCHEMA IF NOT EXISTS AIRBNB_RAW.PROPERTY;
CREATE SCHEMA IF NOT EXISTS AIRBNB_RAW.REVIEWS;

CREATE SCHEMA IF NOT EXISTS AIRBNB_STAGING.PROPERTY;
CREATE SCHEMA IF NOT EXISTS AIRBNB_STAGING.REVIEWS;

CREATE SCHEMA IF NOT EXISTS AIRBNB_MART.PROPERTY;
CREATE SCHEMA IF NOT EXISTS AIRBNB_MART.REVIEWS;



